#cloud-config
autoinstall:
  version: 1
    interactive-sections:
    - network
  identity:
    hostname: Administrador
    username: administrador
    password: '$6$4xdlAaKPLrIIdwhu$KqdfSNIJF5bk7IdSRflRe8.SxMoWBMmfGGrCGNpY.pAtbmugEpjXk2SkKjkoz0tmyR47hLAW5OoeTJMU34y4F0'
locale: pt_BR.UTF-8
  keyboard:
    layout: br
  timezone: America/Sao_Paulo

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - software-properties-common
    - apt-transport-https
    - wget
    - curl
    - vim
    - htop
    - ca-certificates
    - gnupg
    - lsb-release
    - net-tools
    - git
    - libreoffice
    - openssh-server

    # Domínio / AD
    - krb5-user
    - samba
    - sssd
    - sssd-tools
    - libnss-sss
    - libpam-sss
    - ntpdate
    - realmd
    - adcli

    # Dependências do GLPI Agent
    - perl

  snaps:
    - name: spotify
      channel: stable
      classic: false
    - name: discord
      channel: stable
      classic: false
  codecs:
    install: true

  drivers:
    install: true

  updates: all

  shutdown: reboot
